# Where do we want to install file
- hosts: db

# get the facts
  gather_facts: yes

# work from root user
  become: true

# setup db
  tasks:
  - name: Update server
    command: apt-get update -y

  - name: Install mongod
    apt: pkg=mongodb state=present

  - name: mongod.conf edit file
    shell: |
      sudo rm /etc/mongodb.conf
      sudo touch /etc/mongodb.conf
      sudo chmod 666 /etc/mongodb.conf
      cd /etc
      echo "# mongodb.conf


        storage:
          dbPath: /var/lib/mongodb
          journal:
            enabled: true
        systemLog:
          destination: file
          logAppend: true
          path: /var/log/mongodb/mongod.log

        net:
          port: 27017
          bindIp: 0.0.0.0" >> mongodb.conf
      sudo systemctl restart mongodb

  - name: Enable mongod
    command: systemctl enable mongodb
    become: true
